- produceCharacterUnitId: reversi
  targetCharacterId: kllj
  overrideCostumeId: kllj-cstm-0133
  overrideCostumeHeadId: costume_head_kllj-cstm-0133
  conditionSetId: cd-have_i_card-kllj-3-017
- produceCharacterUnitId: reversi
  targetCharacterId: ssmk
  overrideCostumeId: ssmk-cstm-0133
  overrideCostumeHeadId: costume_head_ssmk-cstm-0133
  conditionSetId: cd-have_i_card-ssmk-3-017
