- id: p-card-skin_ido-3_069_mid-ssmk-01
  produceCardId: p_card-02-ido-3_069
  characterId: ssmk
  idolCardSkinId: i_card-skin-ssmk-3-001
  name: 昼下がりのそよ風
  assetId: img_general_skillcard_ido-3_069_mid-ssmk-01
  cutInType: ProduceCardSkinCutInType_Mid
  voiceAssetId: sud_vo_system_cidol-ssmk-3-001_produce_skillcard-01
  viewStartTime: "1786327200000"
  order: "1"
- id: p-card-skin_ido-3_070_mid-hrnm-01
  produceCardId: p_card-01-ido-3_070
  characterId: hrnm
  idolCardSkinId: i_card-skin-hrnm-3-001
  name: 入道雲と、きみ
  assetId: img_general_skillcard_ido-3_070_mid-hrnm-01
  cutInType: ProduceCardSkinCutInType_Mid
  voiceAssetId: sud_vo_system_cidol-hrnm-3-001_produce_skillcard-01
  viewStartTime: "1786327200000"
  order: "2"
- id: p-card-skin_ido-3_073_mid-fktn-01
  produceCardId: p_card-02-ido-3_073
  characterId: fktn
  idolCardSkinId: i_card-skin-fktn-3-002
  name: 夏の宵の線香花火
  assetId: img_general_skillcard_ido-3_073_mid-fktn-01
  cutInType: ProduceCardSkinCutInType_Mid
  voiceAssetId: sud_vo_system_cidol-fktn-3-002_produce_skillcard-01
  viewStartTime: "1786327200000"
  order: "4"
- id: p-card-skin_ido-3_074_mid-kllj-01
  produceCardId: p_card-01-ido-3_074
  characterId: kllj
  idolCardSkinId: i_card-skin-kllj-3-001
  name: はじめてのラムネ
  assetId: img_general_skillcard_ido-3_074_mid-kllj-01
  cutInType: ProduceCardSkinCutInType_Mid
  voiceAssetId: sud_vo_system_cidol-kllj-3-001_produce_skillcard-01
  viewStartTime: "1786327200000"
  order: "3"
