name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          # 确保在仓库根目录下操作
          cd ${{ github.workspace }}
          zip -r masterTrans.zip masterTrans

      - name: Debug ZIP structure (可选)
        run: |
          unzip -l masterTrans.zip | head -n 10  # 查看 ZIP 前10行结构

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: masterTrans.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}